[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bling-utils"
version = "0.2.0"
description = "Utilitários para precificação e upload de imagens para S3"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Gabri" }
]
dependencies = [
  "boto3>=1.28",
  "Pillow>=10.0",
  "python-decouple>=3.8"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["price_generator*", "amazon_s3*"]
